### ISSUE TITLE
Add Repository Command Line Option to Target Specific Repositories

### ISSUE THREAD

**Issue by dealako** [ljharb/repo-report#71]
## Summary

Add Repository Command Line Option to Target Specific Repositories

## Background

To provide additional flexibility and control, a new `--repo-url {repo_url_value}` command-line option (or similar name) could be implemented to only target a specific repository.  This option would indicate that the user only wants to generate a report for this repository.

## Tasks

- [ ] Introduce the new repository command-line option
- [ ] add repository URL validation logic - ensure URL is non-empty and valid
- [ ] review and update logic to only process the specified repository

## Acceptance Criteria

- the repository command-line option is available and is shown in the help output
- the repository command-line option value is validated; must be non-empty, must be a valid repository URL
- the repository command-line option forces the reporting tool to only generate a report for the specified repository

**Comment by pri1311** [comment]
Have an inkling of the changes needed for this. Would like to give it a try.

**Comment by himanshu007-creator** [comment]
Looking into this
